# Copyright (c) Telefonica Digital - CDO QA Team

- name: Script for the deployment of a performance injector in a host
  hosts: jMeter_nodes # Host where deploy the injector

  vars:
    ansible_python_interpreter: /usr/bin/python3.8

  tasks:

    - name: Install pip
      become: yes
      apt:
        name: python3-pip

    - name: Install docker-py package
      become: yes
      pip:
        name: docker-py
        state: latest

    - name: Install Docker
      become: yes
      apt:
        name: "docker.io"
        state: latest

    - name: Add dcip contint key to authorized keys
      authorized_key:
        user: ubuntu
        state: present
        key: '{{ item }}'
      with_file:
        - ssh_keys/dcip_contint.pub

    # Change location to the end
    - name: Check that the ssh keys doesn't exist
      stat:
        path: ~/.ssh/id_rsa.pub
      register: ssh_exists

    - name: Create private and public ssh keys
      command: ssh-keygen -q -f "~/.ssh/id_rsa" -t rsa -C "qacdo-injector-node" -N ''
      when: ssh_exists.stat.exists == False

    - name: Get contents of public ssh key
      become: no
      command: cat ~/.ssh/id_rsa.pub
      register: id_rsa_pub

    - name: Viewing the contents
      debug:
        msg: "{{id_rsa_pub.stdout}}"

    - name: Running the container
      become: yes
      become_user: root
      docker_container:
        name: injector
        image: qatelefonicacdo/jmeter-slave
        state: started
        network_mode: host
        restart: yes
        restart_policy: unless-stopped
        volumes:
          /opt/qacdo/performance/shared_folder:/resources

    - name: Create directory to store the injector
      become: yes
      file:
        path: /opt/qacdo/performance
        state: directory

    - name: Create directory to share with the injector
      become: yes
      file:
        path: /opt/qacdo/performance/shared_folder
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: 0775
